### ISSUE TITLE
Flats Appear Extremely Distorted on Classic Display Mode

### ISSUE THREAD

**Issue by kinker31** [atsb/chocolate-doom-plus-plus#7]
### Background

**Version of Sprinkled Doom:** 3.4.0 Beta

**Operating System and version:** Windows 11, Build 22621.ni_release.220506-1250

**Game:** Doom 2

**Any loaded WADs and mods (please include full command line):** prentral.wad (I use QLD to launch my maps and mods, and doesn't really provide the full command line)

### Bug description

**Observed behavior:**
![DOOM00](https://user-images.githubusercontent.com/16625998/169685015-c4c74993-176d-45d0-a9e5-ec1e0b33092b.png)

**Expected behavior:**
![DOOM01](https://user-images.githubusercontent.com/16625998/169685017-4728876d-7843-42e4-a64c-ceba160d9a16.png)

**Comment by atsb** [comment]
This is now fixed
